- hosts: frontends
  gather_facts: false
  pre_tasks: 
  - name: Include Common Vars
    include_vars: vars/common-vars.yml
  tasks:
  - name: HTTP Request Frontend
    uri:
      url: "{{ frontend_protocol }}://localhost" ## TODO Ping External IP from Bastion/ Workstation
      return_content: yes
      status_code: 200
    register: webpage
    failed_when: apps_validation_content not in webpage.content

  - name: Debug Web Content
    debug: 
      var: webpage.content