- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_info:
      cloud: devstack
      server: frontend*
      filters:
        vm_state: active
    register: osp_frontends

  - name: Curl website
    uri:
      url: "{{ item.public_v4 }}"
    loop: osp_frontends
    register: webpage
    failed_when: 'Ansible has done its job' not in webpage.content
