galaxy_info:
  author: Ashley Menhennett
  description: Engineer
  company: RedHat Homework

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2

  platforms:
  - name: RHEL
    versions:
    - 7
    - 8

  galaxy_tags:
    - ansible
    - tower
    - rhel

dependencies: []