---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  template:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
    mode: 0644
  with_fileglob:
    - "{{role_path}}/templates/repos/*"

- name: install base tools and packages
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ base_packages }}"
